import type {
  City,
  DataSource,
  Merchant,
  Product,
  ServiceProvider,
  WeatherSnapshot
} from "@/lib/types";

export const dataSources: DataSource[] = [
  {
    id: "source-curated-official-links",
    name: "Curated official outbound links",
    sourceType: "manual",
    website: "https://www.openstreetmap.org/copyright",
    licenseNotes:
      "Manual fallback links to official merchant category pages and open data sources. Prices and availability are confirmed off-site.",
    updateFrequency: "Manual review",
    allowedUse: "Information display and official outbound redirects."
  },
  {
    id: "source-chinese-brand-europe-official",
    name: "Chinese-brand official Europe channels",
    sourceType: "manual",
    website: "https://www.midea.com/uk/where-to-buy",
    licenseNotes:
      "Curated official brand pages and distributor/contact directories for Chinese cooling brands active in Europe. No scraping, stock claims, checkout, or price reuse.",
    updateFrequency: "Manual review",
    allowedUse: "Information display, comparison context, and official outbound redirects."
  },
  {
    id: "source-chinese-brand-europe-distributors",
    name: "Chinese-brand Europe distributor partners",
    sourceType: "manual",
    website: "https://haierhvac.eu/news",
    licenseNotes:
      "Curated official distributor, agent, and partner pages for Chinese HVAC brands in Europe. Partner status is based on public source pages and must be confirmed off-site before procurement.",
    updateFrequency: "Manual review",
    allowedUse: "Search, comparison context, and official outbound redirects."
  }
];

export const cities: City[] = [
  {
    id: "city-paris",
    name: "Paris",
    slug: "paris",
    country: "France",
    countryCode: "FR",
    latitude: 48.8566,
    longitude: 2.3522
  },
  {
    id: "city-berlin",
    name: "Berlin",
    slug: "berlin",
    country: "Germany",
    countryCode: "DE",
    latitude: 52.52,
    longitude: 13.405
  },
  {
    id: "city-madrid",
    name: "Madrid",
    slug: "madrid",
    country: "Spain",
    countryCode: "ES",
    latitude: 40.4168,
    longitude: -3.7038
  },
  {
    id: "city-milan",
    name: "Milan",
    slug: "milan",
    country: "Italy",
    countryCode: "IT",
    latitude: 45.4642,
    longitude: 9.19
  },
  {
    id: "city-amsterdam",
    name: "Amsterdam",
    slug: "amsterdam",
    country: "Netherlands",
    countryCode: "NL",
    latitude: 52.3676,
    longitude: 4.9041
  },
  {
    id: "city-london",
    name: "London",
    slug: "london",
    country: "United Kingdom",
    countryCode: "GB",
    latitude: 51.5072,
    longitude: -0.1276
  },
  {
    id: "city-warsaw",
    name: "Warsaw",
    slug: "warsaw",
    country: "Poland",
    countryCode: "PL",
    latitude: 52.2297,
    longitude: 21.0122
  },
  {
    id: "city-krakow",
    name: "Krakow",
    slug: "krakow",
    country: "Poland",
    countryCode: "PL",
    latitude: 50.0647,
    longitude: 19.945
  },
  {
    id: "city-bucharest",
    name: "Bucharest",
    slug: "bucharest",
    country: "Romania",
    countryCode: "RO",
    latitude: 44.4268,
    longitude: 26.1025
  },
  {
    id: "city-helsinki",
    name: "Helsinki",
    slug: "helsinki",
    country: "Finland",
    countryCode: "FI",
    latitude: 60.1699,
    longitude: 24.9384
  },
  {
    id: "city-leicester",
    name: "Leicester",
    slug: "leicester",
    country: "United Kingdom",
    countryCode: "GB",
    latitude: 52.6369,
    longitude: -1.1398
  },
  {
    id: "city-birmingham",
    name: "Birmingham",
    slug: "birmingham",
    country: "United Kingdom",
    countryCode: "GB",
    latitude: 52.4862,
    longitude: -1.8904
  },
  {
    id: "city-budapest",
    name: "Budapest",
    slug: "budapest",
    country: "Hungary",
    countryCode: "HU",
    latitude: 47.4979,
    longitude: 19.0402
  },
  {
    id: "city-belgrade",
    name: "Belgrade",
    slug: "belgrade",
    country: "Serbia",
    countryCode: "RS",
    latitude: 44.8125,
    longitude: 20.4612
  },
  {
    id: "city-vienna",
    name: "Vienna",
    slug: "vienna",
    country: "Austria",
    countryCode: "AT",
    latitude: 48.2082,
    longitude: 16.3738
  },
  {
    id: "city-brussels",
    name: "Brussels",
    slug: "brussels",
    country: "Belgium",
    countryCode: "BE",
    latitude: 50.8503,
    longitude: 4.3517
  },
  {
    id: "city-zagreb",
    name: "Zagreb",
    slug: "zagreb",
    country: "Croatia",
    countryCode: "HR",
    latitude: 45.815,
    longitude: 15.9819
  },
  {
    id: "city-nicosia",
    name: "Nicosia",
    slug: "nicosia",
    country: "Cyprus",
    countryCode: "CY",
    latitude: 35.1856,
    longitude: 33.3823
  }
];

export const merchants: Merchant[] = [
  {
    id: "merchant-leroy-merlin-france",
    name: "Leroy Merlin France",
    slug: "leroy-merlin-france",
    country: "France",
    city: "Paris",
    websiteUrl: "https://www.leroymerlin.fr/produits/chauffage-et-ventilation/",
    logoUrl: "/merchant-placeholder.svg",
    rating: 4.6,
    distanceKm: 2.1,
    dataSourceId: "source-curated-official-links",
    createdAt: "2026-07-01T08:00:00.000Z",
    updatedAt: "2026-07-05T06:10:00.000Z"
  },
  {
    id: "merchant-mediamarkt-germany",
    name: "MediaMarkt Germany",
    slug: "mediamarkt-germany",
    country: "Germany",
    city: "Berlin",
    websiteUrl: "https://www.mediamarkt.de/de/category/heizen-klima-97.html",
    logoUrl: "/merchant-placeholder.svg",
    rating: 4.4,
    distanceKm: 3.8,
    dataSourceId: "source-curated-official-links",
    createdAt: "2026-07-01T08:00:00.000Z",
    updatedAt: "2026-07-05T05:25:00.000Z"
  },
  {
    id: "merchant-el-corte-ingles",
    name: "El Corte Ingles",
    slug: "el-corte-ingles",
    country: "Spain",
    city: "Madrid",
    websiteUrl: "https://www.elcorteingles.es/electrodomesticos/climatizacion/",
    logoUrl: "/merchant-placeholder.svg",
    rating: 4.7,
    distanceKm: 1.4,
    dataSourceId: "source-curated-official-links",
    createdAt: "2026-07-01T08:00:00.000Z",
    updatedAt: "2026-07-05T07:35:00.000Z"
  },
  {
    id: "merchant-unieuro",
    name: "Unieuro",
    slug: "unieuro",
    country: "Italy",
    city: "Milan",
    websiteUrl: "https://www.unieuro.it/online/speciale-clima",
    logoUrl: "/merchant-placeholder.svg",
    rating: 4.2,
    distanceKm: 5.2,
    dataSourceId: "source-curated-official-links",
    createdAt: "2026-07-01T08:00:00.000Z",
    updatedAt: "2026-07-04T16:20:00.000Z"
  },
  {
    id: "merchant-coolblue-netherlands",
    name: "Coolblue Netherlands",
    slug: "coolblue-netherlands",
    country: "Netherlands",
    city: "Amsterdam",
    websiteUrl: "https://www.coolblue.nl/en/air-cooling",
    logoUrl: "/merchant-placeholder.svg",
    rating: 4.5,
    distanceKm: 2.9,
    dataSourceId: "source-curated-official-links",
    createdAt: "2026-07-01T08:00:00.000Z",
    updatedAt: "2026-07-05T04:15:00.000Z"
  },
  {
    id: "merchant-midea-uk-official-channel",
    name: "Midea UK official where-to-buy",
    slug: "midea-uk-official-where-to-buy",
    country: "United Kingdom",
    city: "London",
    coverageArea: "United Kingdom official channel",
    websiteUrl: "https://www.midea.com/uk/where-to-buy",
    logoUrl: "/merchant-placeholder.svg",
    rating: 4.4,
    dataSourceId: "source-chinese-brand-europe-official",
    createdAt: "2026-07-06T08:00:00.000Z",
    updatedAt: "2026-07-06T08:00:00.000Z"
  },
  {
    id: "merchant-haier-italy-official-channel",
    name: "Haier Italy official cooling channel",
    slug: "haier-italy-official-cooling-channel",
    country: "Italy",
    city: "Milan",
    coverageArea: "Italy official channel",
    websiteUrl: "https://www.haier-europe.com/it_IT/pages/condizionatori-portatili",
    logoUrl: "/merchant-placeholder.svg",
    rating: 4.5,
    dataSourceId: "source-chinese-brand-europe-official",
    createdAt: "2026-07-06T08:00:00.000Z",
    updatedAt: "2026-07-06T08:00:00.000Z"
  },
  {
    id: "merchant-tcl-europe-official-channel",
    name: "TCL Europe air conditioner channel",
    slug: "tcl-europe-air-conditioner-channel",
    country: "Europe",
    city: "Europe",
    coverageArea: "Europe-wide official channel",
    websiteUrl: "https://www.tcl.com/eu/en/air-conditioners",
    logoUrl: "/merchant-placeholder.svg",
    rating: 4.3,
    dataSourceId: "source-chinese-brand-europe-official",
    createdAt: "2026-07-06T08:00:00.000Z",
    updatedAt: "2026-07-06T08:00:00.000Z"
  },
  {
    id: "merchant-gree-global-distributor-directory",
    name: "Gree global distributor directory",
    slug: "gree-global-distributor-directory",
    country: "Europe",
    city: "Europe",
    coverageArea: "Europe-wide distributor directory",
    websiteUrl: "https://global.gree.com/channels/140.html",
    logoUrl: "/merchant-placeholder.svg",
    rating: 4.4,
    dataSourceId: "source-chinese-brand-europe-official",
    createdAt: "2026-07-06T08:00:00.000Z",
    updatedAt: "2026-07-06T08:00:00.000Z"
  },
  {
    id: "merchant-aux-global-europe-channel",
    name: "AUX Global air conditioning Europe channel",
    slug: "aux-global-europe-channel",
    country: "Europe",
    city: "Europe",
    coverageArea: "Europe-wide official channel",
    websiteUrl: "https://www.auxair.com/global/",
    logoUrl: "/merchant-placeholder.svg",
    rating: 4.2,
    dataSourceId: "source-chinese-brand-europe-official",
    createdAt: "2026-07-06T08:00:00.000Z",
    updatedAt: "2026-07-06T08:00:00.000Z"
  },
  {
    id: "merchant-haier-wolseley-uk-distributor",
    name: "Wolseley UK - Haier HVAC distributor partner",
    slug: "wolseley-uk-haier-hvac-distributor",
    country: "United Kingdom",
    city: "London",
    coverageArea: "United Kingdom Haier HVAC distributor agent partner",
    websiteUrl:
      "https://haierhvac.eu/news/press-release/haier-hvac-uk-and-wolseley-announce-flagship-partnership-supply-complete",
    logoUrl: "/merchant-placeholder.svg",
    rating: 4.4,
    dataSourceId: "source-chinese-brand-europe-distributors",
    createdAt: "2026-07-06T09:00:00.000Z",
    updatedAt: "2026-07-06T09:00:00.000Z"
  },
  {
    id: "merchant-haier-hawco-uk-distributor",
    name: "Hawco Limited - Haier HVAC distributor",
    slug: "hawco-limited-haier-hvac-distributor",
    country: "United Kingdom",
    city: "London",
    coverageArea: "United Kingdom Haier air conditioning distributor agent partner",
    websiteUrl: "https://haierhvac.eu/news/press-release/haier-hvac-solutions-team-hawco",
    logoUrl: "/merchant-placeholder.svg",
    rating: 4.3,
    dataSourceId: "source-chinese-brand-europe-distributors",
    createdAt: "2026-07-06T09:00:00.000Z",
    updatedAt: "2026-07-06T09:00:00.000Z"
  },
  {
    id: "merchant-haier-masterwatt-netherlands-distributor",
    name: "Masterwatt - Haier HVAC Netherlands partner",
    slug: "masterwatt-haier-hvac-netherlands-partner",
    country: "Netherlands",
    city: "Amsterdam",
    coverageArea: "Netherlands Haier HVAC distributor agent partner",
    websiteUrl:
      "https://haierhvac.eu/news/press-release/haier-hvac-solutions-europe-and-masterwatt-enter-strategic-partnership-drive",
    logoUrl: "/merchant-placeholder.svg",
    rating: 4.3,
    dataSourceId: "source-chinese-brand-europe-distributors",
    createdAt: "2026-07-06T09:00:00.000Z",
    updatedAt: "2026-07-06T09:00:00.000Z"
  },
  {
    id: "merchant-haier-kataikko-finland-distributor",
    name: "Kataikko - Haier HVAC Finnish distributor",
    slug: "kataikko-haier-hvac-finnish-distributor",
    country: "Finland",
    city: "Helsinki",
    coverageArea: "Finland Nordic Haier HVAC distributor agent partner",
    websiteUrl:
      "https://haierhvac.eu/news/press-release/kataikko-new-finnish-distributor-joins-growing-network-haier-hvac-partners",
    logoUrl: "/merchant-placeholder.svg",
    rating: 4.2,
    dataSourceId: "source-chinese-brand-europe-distributors",
    createdAt: "2026-07-06T09:00:00.000Z",
    updatedAt: "2026-07-06T09:00:00.000Z"
  },
  {
    id: "merchant-aux-wienkra-poland-distributor",
    name: "Wienkra - AUX Air Conditioner Polska",
    slug: "wienkra-aux-air-conditioner-polska",
    country: "Poland",
    city: "Krakow",
    coverageArea: "Poland AUX exclusive representative distributor agent partner",
    websiteUrl: "https://auxcool.pl/kontakt/",
    logoUrl: "/merchant-placeholder.svg",
    rating: 4.3,
    dataSourceId: "source-chinese-brand-europe-distributors",
    createdAt: "2026-07-06T09:00:00.000Z",
    updatedAt: "2026-07-06T09:00:00.000Z"
  },
  {
    id: "merchant-aux-clima-polska-distributor",
    name: "Clima Polska - AUX distributor in Poland",
    slug: "clima-polska-aux-distributor",
    country: "Poland",
    city: "Warsaw",
    coverageArea: "Poland Mazovia AUX distributor installation agent partner",
    websiteUrl: "https://www.climapolska.com.pl/en/klimatyzatory-aux/",
    logoUrl: "/merchant-placeholder.svg",
    rating: 4.2,
    dataSourceId: "source-chinese-brand-europe-distributors",
    createdAt: "2026-07-06T09:00:00.000Z",
    updatedAt: "2026-07-06T09:00:00.000Z"
  },
  {
    id: "merchant-aux-macroclima-romania-agent",
    name: "Macroclima Com - AUX Romania agent",
    slug: "macroclima-com-aux-romania-agent",
    country: "Romania",
    city: "Bucharest",
    coverageArea: "Romania AUX distributor agent partner",
    websiteUrl: "https://aux.com.ro/company/",
    logoUrl: "/merchant-placeholder.svg",
    rating: 4.1,
    dataSourceId: "source-chinese-brand-europe-distributors",
    createdAt: "2026-07-06T09:00:00.000Z",
    updatedAt: "2026-07-06T09:00:00.000Z"
  },
  {
    id: "merchant-haier-easy-air-uk-distributor",
    name: "Easy Air Conditioning - Haier HVAC UK distributor",
    slug: "easy-air-conditioning-haier-hvac-uk-distributor",
    country: "United Kingdom",
    city: "Birmingham",
    coverageArea: "United Kingdom Haier HVACR distributor agent partner",
    websiteUrl:
      "https://haierhvac.eu/news/press-release/haier-hvac-solutions-and-easy-air-conditioning-perfect-match",
    logoUrl: "/merchant-placeholder.svg",
    rating: 4.3,
    dataSourceId: "source-chinese-brand-europe-distributors",
    createdAt: "2026-07-06T10:00:00.000Z",
    updatedAt: "2026-07-06T10:00:00.000Z"
  },
  {
    id: "merchant-haier-technoclima-netherlands-distributor",
    name: "Technoclima BV - Haier HVAC Netherlands distributor",
    slug: "technoclima-bv-haier-hvac-netherlands-distributor",
    country: "Netherlands",
    city: "Amsterdam",
    coverageArea: "Netherlands Haier commercial air conditioning distributor agent partner",
    websiteUrl:
      "https://haierhvac.eu/news/press-release/haier-strengthens-its-presence-netherlands-through-strategic-partnership",
    logoUrl: "/merchant-placeholder.svg",
    rating: 4.3,
    dataSourceId: "source-chinese-brand-europe-distributors",
    createdAt: "2026-07-06T10:00:00.000Z",
    updatedAt: "2026-07-06T10:00:00.000Z"
  },
  {
    id: "merchant-haier-klima-hungary-channel",
    name: "KLIMA KFT - Haier HVAC Hungary channel",
    slug: "klima-kft-haier-hvac-hungary-channel",
    country: "Hungary",
    city: "Budapest",
    coverageArea: "Hungary Central-Eastern Europe Haier HVAC distributor service channel",
    websiteUrl:
      "https://haierhvac.eu/news/press-release/haier-hvac-solutions-expands-its-presence-hungarian-market",
    logoUrl: "/merchant-placeholder.svg",
    rating: 4.2,
    dataSourceId: "source-chinese-brand-europe-distributors",
    createdAt: "2026-07-06T10:00:00.000Z",
    updatedAt: "2026-07-06T10:00:00.000Z"
  },
  {
    id: "merchant-midea-zymetric-poland-distributor",
    name: "Zymetric - Midea general representative in Poland",
    slug: "zymetric-midea-general-representative-poland",
    country: "Poland",
    city: "Warsaw",
    coverageArea: "Poland Midea general representative distributor agent partner",
    websiteUrl: "https://zymetric.pl/en/about-company",
    logoUrl: "/merchant-placeholder.svg",
    rating: 4.4,
    dataSourceId: "source-chinese-brand-europe-distributors",
    createdAt: "2026-07-06T10:00:00.000Z",
    updatedAt: "2026-07-06T10:00:00.000Z"
  },
  {
    id: "merchant-midea-smith-brothers-uk-distributor",
    name: "Smith Brothers Stores - Midea UK distributor",
    slug: "smith-brothers-stores-midea-uk-distributor",
    country: "United Kingdom",
    city: "Leicester",
    coverageArea: "United Kingdom Midea HVAC nationwide distributor agent partner",
    websiteUrl: "https://sbs.co.uk/2022/06/smith-brothers-and-midea-sign-game-changing-partnership-deal/",
    logoUrl: "/merchant-placeholder.svg",
    rating: 4.3,
    dataSourceId: "source-chinese-brand-europe-distributors",
    createdAt: "2026-07-06T10:00:00.000Z",
    updatedAt: "2026-07-06T10:00:00.000Z"
  },
  {
    id: "merchant-midea-elcom-serbia-distributor",
    name: "Elcom Trade - Midea Serbia official distributor",
    slug: "elcom-trade-midea-serbia-official-distributor",
    country: "Serbia",
    city: "Belgrade",
    coverageArea: "Serbia Midea official distributor general representative agent partner",
    websiteUrl: "https://elcomtrade.com/en/",
    logoUrl: "/merchant-placeholder.svg",
    rating: 4.2,
    dataSourceId: "source-chinese-brand-europe-distributors",
    createdAt: "2026-07-06T10:00:00.000Z",
    updatedAt: "2026-07-06T10:00:00.000Z"
  },
  {
    id: "merchant-haier-frigentis-austria-directory",
    name: "Frigentis GmbH - Haier Austria distributor",
    slug: "frigentis-gmbh-haier-austria-distributor",
    country: "Austria",
    city: "Vienna",
    coverageArea: "Austria Haier official where-to-buy distributor directory",
    websiteUrl: "https://haierhvac.eu/where-to-buy",
    logoUrl: "/merchant-placeholder.svg",
    rating: 4.1,
    dataSourceId: "source-chinese-brand-europe-distributors",
    createdAt: "2026-07-06T10:00:00.000Z",
    updatedAt: "2026-07-06T10:00:00.000Z"
  },
  {
    id: "merchant-haier-frigro-belgium-directory",
    name: "Frigro NV - Haier Belgium distributor",
    slug: "frigro-nv-haier-belgium-distributor",
    country: "Belgium",
    city: "Brussels",
    coverageArea: "Belgium Haier official where-to-buy distributor directory",
    websiteUrl: "https://haierhvac.eu/where-to-buy",
    logoUrl: "/merchant-placeholder.svg",
    rating: 4.1,
    dataSourceId: "source-chinese-brand-europe-distributors",
    createdAt: "2026-07-06T10:00:00.000Z",
    updatedAt: "2026-07-06T10:00:00.000Z"
  },
  {
    id: "merchant-haier-mb-frigo-croatia-directory",
    name: "MB Frigo Grupa - Haier Croatia distributor",
    slug: "mb-frigo-grupa-haier-croatia-distributor",
    country: "Croatia",
    city: "Zagreb",
    coverageArea: "Croatia Haier official where-to-buy distributor directory",
    websiteUrl: "https://haierhvac.eu/where-to-buy",
    logoUrl: "/merchant-placeholder.svg",
    rating: 4.1,
    dataSourceId: "source-chinese-brand-europe-distributors",
    createdAt: "2026-07-06T10:00:00.000Z",
    updatedAt: "2026-07-06T10:00:00.000Z"
  },
  {
    id: "merchant-haier-cooltec-cyprus-directory",
    name: "Cooltec Energy Systems - Haier Cyprus distributor",
    slug: "cooltec-energy-systems-haier-cyprus-distributor",
    country: "Cyprus",
    city: "Nicosia",
    coverageArea: "Cyprus Haier official where-to-buy distributor directory",
    websiteUrl: "https://haierhvac.eu/where-to-buy",
    logoUrl: "/merchant-placeholder.svg",
    rating: 4.1,
    dataSourceId: "source-chinese-brand-europe-distributors",
    createdAt: "2026-07-06T10:00:00.000Z",
    updatedAt: "2026-07-06T10:00:00.000Z"
  }
];

export const products: Product[] = [
  {
    id: "product-leroy-merlin-cooling-category",
    merchantId: "merchant-leroy-merlin-france",
    category: "portable-ac",
    name: "Portable cooling category at Leroy Merlin France",
    slug: "portable-cooling-leroy-merlin-france",
    brand: "Leroy Merlin",
    description:
      "Official cooling and ventilation category page. Final price, delivery, and availability are confirmed on Leroy Merlin.",
    price: 0,
    currency: "EUR",
    deliveryEstimate: "Confirmed on official site",
    deliveryHours: 24,
    pickupAvailable: true,
    installationAvailable: false,
    merchantProductUrl: "https://www.leroymerlin.fr/produits/chauffage-et-ventilation/climatisation/",
    imageUrl: "/product-placeholder.svg",
    sourceUpdatedAt: "2026-07-05T06:10:00.000Z",
    createdAt: "2026-07-01T08:00:00.000Z",
    updatedAt: "2026-07-05T06:10:00.000Z"
  },
  {
    id: "product-mediamarkt-air-cooling-category",
    merchantId: "merchant-mediamarkt-germany",
    category: "fan",
    name: "Air cooling category at MediaMarkt Germany",
    slug: "air-cooling-mediamarkt-germany",
    brand: "MediaMarkt",
    description:
      "Official heating and air cooling category page. Final price, delivery, and availability are confirmed on MediaMarkt.",
    price: 0,
    currency: "EUR",
    deliveryEstimate: "Confirmed on official site",
    deliveryHours: 24,
    pickupAvailable: true,
    installationAvailable: false,
    merchantProductUrl: "https://www.mediamarkt.de/de/category/heizen-klima-97.html",
    imageUrl: "/product-placeholder.svg",
    sourceUpdatedAt: "2026-07-05T05:25:00.000Z",
    createdAt: "2026-07-01T08:00:00.000Z",
    updatedAt: "2026-07-05T05:25:00.000Z"
  },
  {
    id: "product-el-corte-ingles-cooling-category",
    merchantId: "merchant-el-corte-ingles",
    category: "portable-ac",
    name: "Climate control category at El Corte Ingles",
    slug: "climate-control-el-corte-ingles",
    brand: "El Corte Ingles",
    description:
      "Official climate control category page. Final price, delivery, and availability are confirmed on El Corte Ingles.",
    price: 0,
    currency: "EUR",
    deliveryEstimate: "Confirmed on official site",
    deliveryHours: 6,
    pickupAvailable: true,
    installationAvailable: true,
    merchantProductUrl: "https://www.elcorteingles.es/electrodomesticos/climatizacion/",
    imageUrl: "/product-placeholder.svg",
    sourceUpdatedAt: "2026-07-05T07:35:00.000Z",
    createdAt: "2026-07-01T08:00:00.000Z",
    updatedAt: "2026-07-05T07:35:00.000Z"
  },
  {
    id: "product-unieuro-climate-category",
    merchantId: "merchant-unieuro",
    category: "ac-installation",
    name: "Climate products at Unieuro",
    slug: "climate-products-unieuro",
    brand: "Unieuro",
    description:
      "Official climate category page. Final price, delivery, and availability are confirmed on Unieuro.",
    price: 0,
    currency: "EUR",
    deliveryEstimate: "Confirmed on official site",
    deliveryHours: 4,
    pickupAvailable: true,
    installationAvailable: true,
    merchantProductUrl: "https://www.unieuro.it/online/speciale-clima",
    imageUrl: "/product-placeholder.svg",
    sourceUpdatedAt: "2026-07-04T16:20:00.000Z",
    createdAt: "2026-07-01T08:00:00.000Z",
    updatedAt: "2026-07-04T16:20:00.000Z"
  },
  {
    id: "product-coolblue-air-cooling-category",
    merchantId: "merchant-coolblue-netherlands",
    category: "fan",
    name: "Air cooling category at Coolblue Netherlands",
    slug: "air-cooling-coolblue-netherlands",
    brand: "Coolblue",
    description:
      "Official air cooling category page. Final price, delivery, and availability are confirmed on Coolblue.",
    price: 0,
    currency: "EUR",
    deliveryEstimate: "Confirmed on official site",
    deliveryHours: 20,
    pickupAvailable: true,
    installationAvailable: false,
    merchantProductUrl: "https://www.coolblue.nl/en/air-cooling",
    imageUrl: "/product-placeholder.svg",
    sourceUpdatedAt: "2026-07-05T04:15:00.000Z",
    createdAt: "2026-07-01T08:00:00.000Z",
    updatedAt: "2026-07-05T04:15:00.000Z"
  },
  {
    id: "product-midea-uk-where-to-buy",
    merchantId: "merchant-midea-uk-official-channel",
    category: "portable-ac",
    name: "Midea UK official air conditioning where-to-buy",
    slug: "midea-uk-air-conditioning-where-to-buy",
    brand: "Midea",
    description:
      "Chinese-brand official UK where-to-buy page for Midea air conditioning and renewables. Final merchant, price, and availability are confirmed on Midea or its listed partners.",
    price: 0,
    currency: "EUR",
    deliveryEstimate: "Confirmed on official channel",
    deliveryHours: 24,
    pickupAvailable: false,
    installationAvailable: true,
    merchantProductUrl: "https://www.midea.com/uk/where-to-buy",
    imageUrl: "/product-placeholder.svg",
    sourceUpdatedAt: "2026-07-06T08:00:00.000Z",
    createdAt: "2026-07-06T08:00:00.000Z",
    updatedAt: "2026-07-06T08:00:00.000Z"
  },
  {
    id: "product-haier-italy-portable-ac",
    merchantId: "merchant-haier-italy-official-channel",
    category: "portable-ac",
    name: "Haier Italy portable air conditioners",
    slug: "haier-italy-portable-air-conditioners",
    brand: "Haier",
    description:
      "Chinese-brand official Haier Italy portable air conditioner page. Final product details, merchant options, and availability are confirmed on Haier Europe.",
    price: 0,
    currency: "EUR",
    deliveryEstimate: "Confirmed on official channel",
    deliveryHours: 24,
    pickupAvailable: false,
    installationAvailable: false,
    merchantProductUrl: "https://www.haier-europe.com/it_IT/pages/condizionatori-portatili",
    imageUrl: "/product-placeholder.svg",
    sourceUpdatedAt: "2026-07-06T08:00:00.000Z",
    createdAt: "2026-07-06T08:00:00.000Z",
    updatedAt: "2026-07-06T08:00:00.000Z"
  },
  {
    id: "product-tcl-europe-air-conditioners",
    merchantId: "merchant-tcl-europe-official-channel",
    category: "portable-ac",
    name: "TCL Europe air conditioners",
    slug: "tcl-europe-air-conditioners",
    brand: "TCL",
    description:
      "Chinese-brand official TCL Europe air conditioner range covering portable, wall-mounted, and light commercial options. Final dealer and availability details are confirmed off-site.",
    price: 0,
    currency: "EUR",
    deliveryEstimate: "Confirmed on official channel",
    deliveryHours: 24,
    pickupAvailable: false,
    installationAvailable: true,
    merchantProductUrl: "https://www.tcl.com/eu/en/air-conditioners",
    imageUrl: "/product-placeholder.svg",
    sourceUpdatedAt: "2026-07-06T08:00:00.000Z",
    createdAt: "2026-07-06T08:00:00.000Z",
    updatedAt: "2026-07-06T08:00:00.000Z"
  },
  {
    id: "product-gree-global-distributors",
    merchantId: "merchant-gree-global-distributor-directory",
    category: "ac-installation",
    name: "Gree official global distributor directory",
    slug: "gree-official-global-distributor-directory",
    brand: "Gree",
    description:
      "Chinese-brand official Gree distributor directory for finding regional air-conditioner channels. Final partner, product, and support details are confirmed on Gree or listed distributors.",
    price: 0,
    currency: "EUR",
    deliveryEstimate: "Confirmed by listed distributor",
    deliveryHours: 24,
    pickupAvailable: false,
    installationAvailable: true,
    merchantProductUrl: "https://global.gree.com/channels/140.html",
    imageUrl: "/product-placeholder.svg",
    sourceUpdatedAt: "2026-07-06T08:00:00.000Z",
    createdAt: "2026-07-06T08:00:00.000Z",
    updatedAt: "2026-07-06T08:00:00.000Z"
  },
  {
    id: "product-aux-global-europe-air-conditioning",
    merchantId: "merchant-aux-global-europe-channel",
    category: "ac-installation",
    name: "AUX Global air conditioning Europe channel",
    slug: "aux-global-europe-air-conditioning-channel",
    brand: "AUX",
    description:
      "Chinese-brand official AUX air conditioning channel with Europe expansion and localized installation-service context. Final service and distributor details are confirmed off-site.",
    price: 0,
    currency: "EUR",
    deliveryEstimate: "Confirmed on official channel",
    deliveryHours: 24,
    pickupAvailable: false,
    installationAvailable: true,
    merchantProductUrl: "https://www.auxair.com/global/",
    imageUrl: "/product-placeholder.svg",
    sourceUpdatedAt: "2026-07-06T08:00:00.000Z",
    createdAt: "2026-07-06T08:00:00.000Z",
    updatedAt: "2026-07-06T08:00:00.000Z"
  },
  {
    id: "product-haier-wolseley-uk-distributor",
    merchantId: "merchant-haier-wolseley-uk-distributor",
    category: "ac-installation",
    name: "Haier HVAC via Wolseley UK distributor partner",
    slug: "haier-hvac-wolseley-uk-distributor",
    brand: "Haier",
    description:
      "Chinese-brand Haier HVAC distributor partner entry for the UK. Distributor status, product range, pricing, and availability must be confirmed on the official partner source.",
    price: 0,
    currency: "EUR",
    deliveryEstimate: "Confirmed by distributor partner",
    deliveryHours: 24,
    pickupAvailable: false,
    installationAvailable: true,
    merchantProductUrl:
      "https://haierhvac.eu/news/press-release/haier-hvac-uk-and-wolseley-announce-flagship-partnership-supply-complete",
    imageUrl: "/product-placeholder.svg",
    sourceUpdatedAt: "2026-07-06T09:00:00.000Z",
    createdAt: "2026-07-06T09:00:00.000Z",
    updatedAt: "2026-07-06T09:00:00.000Z"
  },
  {
    id: "product-haier-hawco-uk-distributor",
    merchantId: "merchant-haier-hawco-uk-distributor",
    category: "ac-installation",
    name: "Haier HVAC via Hawco UK distributor",
    slug: "haier-hvac-hawco-uk-distributor",
    brand: "Haier",
    description:
      "Chinese-brand Haier HVAC distributor entry for the UK. Final partner details, technical range, pricing, and availability are confirmed off-site.",
    price: 0,
    currency: "EUR",
    deliveryEstimate: "Confirmed by distributor partner",
    deliveryHours: 24,
    pickupAvailable: false,
    installationAvailable: true,
    merchantProductUrl: "https://haierhvac.eu/news/press-release/haier-hvac-solutions-team-hawco",
    imageUrl: "/product-placeholder.svg",
    sourceUpdatedAt: "2026-07-06T09:00:00.000Z",
    createdAt: "2026-07-06T09:00:00.000Z",
    updatedAt: "2026-07-06T09:00:00.000Z"
  },
  {
    id: "product-haier-masterwatt-netherlands-partner",
    merchantId: "merchant-haier-masterwatt-netherlands-distributor",
    category: "ac-installation",
    name: "Haier HVAC via Masterwatt Netherlands partner",
    slug: "haier-hvac-masterwatt-netherlands-partner",
    brand: "Haier",
    description:
      "Chinese-brand Haier HVAC distributor partner entry for the Netherlands. Final product, installation, and availability details are confirmed on the official partner source.",
    price: 0,
    currency: "EUR",
    deliveryEstimate: "Confirmed by distributor partner",
    deliveryHours: 24,
    pickupAvailable: false,
    installationAvailable: true,
    merchantProductUrl:
      "https://haierhvac.eu/news/press-release/haier-hvac-solutions-europe-and-masterwatt-enter-strategic-partnership-drive",
    imageUrl: "/product-placeholder.svg",
    sourceUpdatedAt: "2026-07-06T09:00:00.000Z",
    createdAt: "2026-07-06T09:00:00.000Z",
    updatedAt: "2026-07-06T09:00:00.000Z"
  },
  {
    id: "product-haier-kataikko-finland-distributor",
    merchantId: "merchant-haier-kataikko-finland-distributor",
    category: "ac-installation",
    name: "Haier HVAC via Kataikko Finnish distributor",
    slug: "haier-hvac-kataikko-finnish-distributor",
    brand: "Haier",
    description:
      "Chinese-brand Haier HVAC distributor entry for Finland and Nordic discovery. Product range, partner service, and availability are confirmed off-site.",
    price: 0,
    currency: "EUR",
    deliveryEstimate: "Confirmed by distributor partner",
    deliveryHours: 24,
    pickupAvailable: false,
    installationAvailable: true,
    merchantProductUrl:
      "https://haierhvac.eu/news/press-release/kataikko-new-finnish-distributor-joins-growing-network-haier-hvac-partners",
    imageUrl: "/product-placeholder.svg",
    sourceUpdatedAt: "2026-07-06T09:00:00.000Z",
    createdAt: "2026-07-06T09:00:00.000Z",
    updatedAt: "2026-07-06T09:00:00.000Z"
  },
  {
    id: "product-aux-wienkra-poland-distributor",
    merchantId: "merchant-aux-wienkra-poland-distributor",
    category: "ac-installation",
    name: "AUX via Wienkra Poland representative",
    slug: "aux-wienkra-poland-representative",
    brand: "AUX",
    description:
      "Chinese-brand AUX representative and distributor entry for Poland. Final product, installation, service, and availability information is confirmed on the official channel.",
    price: 0,
    currency: "EUR",
    deliveryEstimate: "Confirmed by distributor partner",
    deliveryHours: 24,
    pickupAvailable: false,
    installationAvailable: true,
    merchantProductUrl: "https://auxcool.pl/kontakt/",
    imageUrl: "/product-placeholder.svg",
    sourceUpdatedAt: "2026-07-06T09:00:00.000Z",
    createdAt: "2026-07-06T09:00:00.000Z",
    updatedAt: "2026-07-06T09:00:00.000Z"
  },
  {
    id: "product-aux-clima-polska-distributor",
    merchantId: "merchant-aux-clima-polska-distributor",
    category: "ac-installation",
    name: "AUX via Clima Polska distributor",
    slug: "aux-clima-polska-distributor",
    brand: "AUX",
    description:
      "Chinese-brand AUX distributor and installation partner entry for Poland. Final service area, product range, and availability are confirmed on Clima Polska.",
    price: 0,
    currency: "EUR",
    deliveryEstimate: "Confirmed by distributor partner",
    deliveryHours: 24,
    pickupAvailable: false,
    installationAvailable: true,
    merchantProductUrl: "https://www.climapolska.com.pl/en/klimatyzatory-aux/",
    imageUrl: "/product-placeholder.svg",
    sourceUpdatedAt: "2026-07-06T09:00:00.000Z",
    createdAt: "2026-07-06T09:00:00.000Z",
    updatedAt: "2026-07-06T09:00:00.000Z"
  },
  {
    id: "product-aux-macroclima-romania-agent",
    merchantId: "merchant-aux-macroclima-romania-agent",
    category: "ac-installation",
    name: "AUX via Macroclima Com Romania agent",
    slug: "aux-macroclima-com-romania-agent",
    brand: "AUX",
    description:
      "Chinese-brand AUX Romania agent entry. Final distributor status, installation service, product range, and availability are confirmed on the official Romania channel.",
    price: 0,
    currency: "EUR",
    deliveryEstimate: "Confirmed by distributor partner",
    deliveryHours: 24,
    pickupAvailable: false,
    installationAvailable: true,
    merchantProductUrl: "https://aux.com.ro/company/",
    imageUrl: "/product-placeholder.svg",
    sourceUpdatedAt: "2026-07-06T09:00:00.000Z",
    createdAt: "2026-07-06T09:00:00.000Z",
    updatedAt: "2026-07-06T09:00:00.000Z"
  },
  {
    id: "product-haier-easy-air-uk-distributor",
    merchantId: "merchant-haier-easy-air-uk-distributor",
    category: "ac-installation",
    name: "Haier HVAC via Easy Air Conditioning UK distributor",
    slug: "haier-hvac-easy-air-conditioning-uk-distributor",
    brand: "Haier",
    description:
      "Chinese-brand Haier HVAC distributor entry for the UK. Final product range, technical support, pricing, and availability are confirmed on the official partner source.",
    price: 0,
    currency: "EUR",
    deliveryEstimate: "Confirmed by distributor partner",
    deliveryHours: 24,
    pickupAvailable: false,
    installationAvailable: true,
    merchantProductUrl:
      "https://haierhvac.eu/news/press-release/haier-hvac-solutions-and-easy-air-conditioning-perfect-match",
    imageUrl: "/product-placeholder.svg",
    sourceUpdatedAt: "2026-07-06T10:00:00.000Z",
    createdAt: "2026-07-06T10:00:00.000Z",
    updatedAt: "2026-07-06T10:00:00.000Z"
  },
  {
    id: "product-haier-technoclima-netherlands-distributor",
    merchantId: "merchant-haier-technoclima-netherlands-distributor",
    category: "ac-installation",
    name: "Haier HVAC via Technoclima Netherlands distributor",
    slug: "haier-hvac-technoclima-netherlands-distributor",
    brand: "Haier",
    description:
      "Chinese-brand Haier commercial air-conditioning and heat-pump distributor entry for the Netherlands. Final availability and installer support are confirmed off-site.",
    price: 0,
    currency: "EUR",
    deliveryEstimate: "Confirmed by distributor partner",
    deliveryHours: 24,
    pickupAvailable: false,
    installationAvailable: true,
    merchantProductUrl:
      "https://haierhvac.eu/news/press-release/haier-strengthens-its-presence-netherlands-through-strategic-partnership",
    imageUrl: "/product-placeholder.svg",
    sourceUpdatedAt: "2026-07-06T10:00:00.000Z",
    createdAt: "2026-07-06T10:00:00.000Z",
    updatedAt: "2026-07-06T10:00:00.000Z"
  },
  {
    id: "product-haier-klima-hungary-channel",
    merchantId: "merchant-haier-klima-hungary-channel",
    category: "ac-installation",
    name: "Haier HVAC via KLIMA KFT Hungary channel",
    slug: "haier-hvac-klima-kft-hungary-channel",
    brand: "Haier",
    description:
      "Chinese-brand Haier HVAC channel entry for Hungary and Central-Eastern Europe. Final service, installation, and product availability are confirmed on the official source.",
    price: 0,
    currency: "EUR",
    deliveryEstimate: "Confirmed by local channel",
    deliveryHours: 24,
    pickupAvailable: false,
    installationAvailable: true,
    merchantProductUrl:
      "https://haierhvac.eu/news/press-release/haier-hvac-solutions-expands-its-presence-hungarian-market",
    imageUrl: "/product-placeholder.svg",
    sourceUpdatedAt: "2026-07-06T10:00:00.000Z",
    createdAt: "2026-07-06T10:00:00.000Z",
    updatedAt: "2026-07-06T10:00:00.000Z"
  },
  {
    id: "product-midea-zymetric-poland-distributor",
    merchantId: "merchant-midea-zymetric-poland-distributor",
    category: "ac-installation",
    name: "Midea via Zymetric Poland general representative",
    slug: "midea-zymetric-poland-general-representative",
    brand: "Midea",
    description:
      "Chinese-brand Midea general representative and distributor entry for Poland. Final partner network, product range, pricing, and availability are confirmed on Zymetric.",
    price: 0,
    currency: "EUR",
    deliveryEstimate: "Confirmed by distributor partner",
    deliveryHours: 24,
    pickupAvailable: false,
    installationAvailable: true,
    merchantProductUrl: "https://zymetric.pl/en/about-company",
    imageUrl: "/product-placeholder.svg",
    sourceUpdatedAt: "2026-07-06T10:00:00.000Z",
    createdAt: "2026-07-06T10:00:00.000Z",
    updatedAt: "2026-07-06T10:00:00.000Z"
  },
  {
    id: "product-midea-smith-brothers-uk-distributor",
    merchantId: "merchant-midea-smith-brothers-uk-distributor",
    category: "ac-installation",
    name: "Midea HVAC via Smith Brothers Stores UK distributor",
    slug: "midea-hvac-smith-brothers-stores-uk-distributor",
    brand: "Midea",
    description:
      "Chinese-brand Midea nationwide HVAC distributor entry for the UK. Final availability, training, product range, and commercial terms are confirmed off-site.",
    price: 0,
    currency: "EUR",
    deliveryEstimate: "Confirmed by distributor partner",
    deliveryHours: 24,
    pickupAvailable: false,
    installationAvailable: true,
    merchantProductUrl: "https://sbs.co.uk/2022/06/smith-brothers-and-midea-sign-game-changing-partnership-deal/",
    imageUrl: "/product-placeholder.svg",
    sourceUpdatedAt: "2026-07-06T10:00:00.000Z",
    createdAt: "2026-07-06T10:00:00.000Z",
    updatedAt: "2026-07-06T10:00:00.000Z"
  },
  {
    id: "product-midea-elcom-serbia-distributor",
    merchantId: "merchant-midea-elcom-serbia-distributor",
    category: "ac-installation",
    name: "Midea via Elcom Trade Serbia official distributor",
    slug: "midea-elcom-trade-serbia-official-distributor",
    brand: "Midea",
    description:
      "Chinese-brand Midea official distributor entry for Serbia. Final support, import, service, pricing, and product availability are confirmed on Elcom Trade.",
    price: 0,
    currency: "EUR",
    deliveryEstimate: "Confirmed by distributor partner",
    deliveryHours: 24,
    pickupAvailable: false,
    installationAvailable: true,
    merchantProductUrl: "https://elcomtrade.com/en/",
    imageUrl: "/product-placeholder.svg",
    sourceUpdatedAt: "2026-07-06T10:00:00.000Z",
    createdAt: "2026-07-06T10:00:00.000Z",
    updatedAt: "2026-07-06T10:00:00.000Z"
  },
  {
    id: "product-haier-frigentis-austria-directory",
    merchantId: "merchant-haier-frigentis-austria-directory",
    category: "ac-installation",
    name: "Haier via Frigentis Austria distributor directory",
    slug: "haier-frigentis-austria-distributor-directory",
    brand: "Haier",
    description:
      "Chinese-brand Haier official where-to-buy directory entry for Austria. Final product, support, pricing, and availability are confirmed by the listed distributor.",
    price: 0,
    currency: "EUR",
    deliveryEstimate: "Confirmed by official directory",
    deliveryHours: 24,
    pickupAvailable: false,
    installationAvailable: true,
    merchantProductUrl: "https://haierhvac.eu/where-to-buy",
    imageUrl: "/product-placeholder.svg",
    sourceUpdatedAt: "2026-07-06T10:00:00.000Z",
    createdAt: "2026-07-06T10:00:00.000Z",
    updatedAt: "2026-07-06T10:00:00.000Z"
  },
  {
    id: "product-haier-frigro-belgium-directory",
    merchantId: "merchant-haier-frigro-belgium-directory",
    category: "ac-installation",
    name: "Haier via Frigro Belgium distributor directory",
    slug: "haier-frigro-belgium-distributor-directory",
    brand: "Haier",
    description:
      "Chinese-brand Haier official where-to-buy directory entry for Belgium. Final partner details and availability are confirmed by the listed distributor.",
    price: 0,
    currency: "EUR",
    deliveryEstimate: "Confirmed by official directory",
    deliveryHours: 24,
    pickupAvailable: false,
    installationAvailable: true,
    merchantProductUrl: "https://haierhvac.eu/where-to-buy",
    imageUrl: "/product-placeholder.svg",
    sourceUpdatedAt: "2026-07-06T10:00:00.000Z",
    createdAt: "2026-07-06T10:00:00.000Z",
    updatedAt: "2026-07-06T10:00:00.000Z"
  },
  {
    id: "product-haier-mb-frigo-croatia-directory",
    merchantId: "merchant-haier-mb-frigo-croatia-directory",
    category: "ac-installation",
    name: "Haier via MB Frigo Croatia distributor directory",
    slug: "haier-mb-frigo-croatia-distributor-directory",
    brand: "Haier",
    description:
      "Chinese-brand Haier official where-to-buy directory entry for Croatia. Final product range, support, and availability are confirmed off-site.",
    price: 0,
    currency: "EUR",
    deliveryEstimate: "Confirmed by official directory",
    deliveryHours: 24,
    pickupAvailable: false,
    installationAvailable: true,
    merchantProductUrl: "https://haierhvac.eu/where-to-buy",
    imageUrl: "/product-placeholder.svg",
    sourceUpdatedAt: "2026-07-06T10:00:00.000Z",
    createdAt: "2026-07-06T10:00:00.000Z",
    updatedAt: "2026-07-06T10:00:00.000Z"
  },
  {
    id: "product-haier-cooltec-cyprus-directory",
    merchantId: "merchant-haier-cooltec-cyprus-directory",
    category: "ac-installation",
    name: "Haier via Cooltec Cyprus distributor directory",
    slug: "haier-cooltec-cyprus-distributor-directory",
    brand: "Haier",
    description:
      "Chinese-brand Haier official where-to-buy directory entry for Cyprus. Final distributor details, service area, and availability are confirmed on the official directory.",
    price: 0,
    currency: "EUR",
    deliveryEstimate: "Confirmed by official directory",
    deliveryHours: 24,
    pickupAvailable: false,
    installationAvailable: true,
    merchantProductUrl: "https://haierhvac.eu/where-to-buy",
    imageUrl: "/product-placeholder.svg",
    sourceUpdatedAt: "2026-07-06T10:00:00.000Z",
    createdAt: "2026-07-06T10:00:00.000Z",
    updatedAt: "2026-07-06T10:00:00.000Z"
  }
];

export const serviceProviders: ServiceProvider[] = [
  {
    id: "service-paris-install",
    name: "OpenStreetMap HVAC and cooling services in Paris",
    slug: "paris-rapid-ac-install",
    serviceType: "installation",
    country: "France",
    city: "Paris",
    websiteUrl: "https://www.openstreetmap.org/search?query=hvac%20Paris",
    rating: 4.8,
    distanceKm: 2.7,
    emergencyAvailable: true,
    estimatedResponseTime: "Same day callback",
    responseHours: 6,
    sourceUpdatedAt: "2026-07-05T05:50:00.000Z"
  },
  {
    id: "service-berlin-repair",
    name: "OpenStreetMap cooling repair services in Berlin",
    slug: "berlin-cool-repair",
    serviceType: "repair",
    country: "Germany",
    city: "Berlin",
    websiteUrl: "https://www.openstreetmap.org/search?query=air%20conditioning%20repair%20Berlin",
    rating: 4.5,
    distanceKm: 4.1,
    emergencyAvailable: true,
    estimatedResponseTime: "Within 12 hours",
    responseHours: 12,
    sourceUpdatedAt: "2026-07-05T03:40:00.000Z"
  },
  {
    id: "service-madrid-install",
    name: "OpenStreetMap AC installation services in Madrid",
    slug: "madrid-heat-relief-installers",
    serviceType: "installation",
    country: "Spain",
    city: "Madrid",
    websiteUrl: "https://www.openstreetmap.org/search?query=aire%20acondicionado%20instalacion%20Madrid",
    rating: 4.6,
    distanceKm: 3.2,
    emergencyAvailable: true,
    estimatedResponseTime: "Today if booked on provider site",
    responseHours: 8,
    sourceUpdatedAt: "2026-07-05T07:00:00.000Z"
  },
  {
    id: "service-amsterdam-cooling-center",
    name: "Amsterdam Public Cooling Center Finder",
    slug: "amsterdam-public-cooling-center-finder",
    serviceType: "cooling-center",
    country: "Netherlands",
    city: "Amsterdam",
    websiteUrl: "https://www.amsterdam.nl/en/news/where-cool-down-during-hot-weather/",
    rating: 4.3,
    distanceKm: 1.1,
    emergencyAvailable: true,
    estimatedResponseTime: "Open locations listed on official site",
    responseHours: 1,
    sourceUpdatedAt: "2026-07-05T04:45:00.000Z"
  }
];

export const weatherSnapshots: WeatherSnapshot[] = [
  {
    id: "weather-paris",
    cityId: "city-paris",
    temperatureC: 36,
    condition: "Heat advisory",
    alertLevel: "high",
    provider: "Demo weather provider",
    observedAt: "2026-07-05T07:00:00.000Z"
  },
  {
    id: "weather-berlin",
    cityId: "city-berlin",
    temperatureC: 33,
    condition: "Hot and dry",
    alertLevel: "watch",
    provider: "Demo weather provider",
    observedAt: "2026-07-05T07:00:00.000Z"
  },
  {
    id: "weather-madrid",
    cityId: "city-madrid",
    temperatureC: 40,
    condition: "Extreme heat warning",
    alertLevel: "extreme",
    provider: "Demo weather provider",
    observedAt: "2026-07-05T07:00:00.000Z"
  },
  {
    id: "weather-milan",
    cityId: "city-milan",
    temperatureC: 35,
    condition: "Heat advisory",
    alertLevel: "high",
    provider: "Demo weather provider",
    observedAt: "2026-07-05T07:00:00.000Z"
  },
  {
    id: "weather-amsterdam",
    cityId: "city-amsterdam",
    temperatureC: 29,
    condition: "Warm",
    alertLevel: "normal",
    provider: "Demo weather provider",
    observedAt: "2026-07-05T07:00:00.000Z"
  },
  {
    id: "weather-london",
    cityId: "city-london",
    temperatureC: 28,
    condition: "Warm",
    alertLevel: "normal",
    provider: "Demo weather provider",
    observedAt: "2026-07-06T07:00:00.000Z"
  },
  {
    id: "weather-warsaw",
    cityId: "city-warsaw",
    temperatureC: 31,
    condition: "Warm",
    alertLevel: "watch",
    provider: "Demo weather provider",
    observedAt: "2026-07-06T07:00:00.000Z"
  },
  {
    id: "weather-krakow",
    cityId: "city-krakow",
    temperatureC: 30,
    condition: "Warm",
    alertLevel: "watch",
    provider: "Demo weather provider",
    observedAt: "2026-07-06T07:00:00.000Z"
  },
  {
    id: "weather-bucharest",
    cityId: "city-bucharest",
    temperatureC: 36,
    condition: "Heat advisory",
    alertLevel: "high",
    provider: "Demo weather provider",
    observedAt: "2026-07-06T07:00:00.000Z"
  },
  {
    id: "weather-helsinki",
    cityId: "city-helsinki",
    temperatureC: 25,
    condition: "Mild",
    alertLevel: "normal",
    provider: "Demo weather provider",
    observedAt: "2026-07-06T07:00:00.000Z"
  },
  {
    id: "weather-leicester",
    cityId: "city-leicester",
    temperatureC: 27,
    condition: "Warm",
    alertLevel: "normal",
    provider: "Demo weather provider",
    observedAt: "2026-07-06T07:00:00.000Z"
  },
  {
    id: "weather-birmingham",
    cityId: "city-birmingham",
    temperatureC: 27,
    condition: "Warm",
    alertLevel: "normal",
    provider: "Demo weather provider",
    observedAt: "2026-07-06T07:00:00.000Z"
  },
  {
    id: "weather-budapest",
    cityId: "city-budapest",
    temperatureC: 34,
    condition: "Hot",
    alertLevel: "watch",
    provider: "Demo weather provider",
    observedAt: "2026-07-06T07:00:00.000Z"
  },
  {
    id: "weather-belgrade",
    cityId: "city-belgrade",
    temperatureC: 35,
    condition: "Heat advisory",
    alertLevel: "high",
    provider: "Demo weather provider",
    observedAt: "2026-07-06T07:00:00.000Z"
  },
  {
    id: "weather-vienna",
    cityId: "city-vienna",
    temperatureC: 32,
    condition: "Warm",
    alertLevel: "watch",
    provider: "Demo weather provider",
    observedAt: "2026-07-06T07:00:00.000Z"
  },
  {
    id: "weather-brussels",
    cityId: "city-brussels",
    temperatureC: 28,
    condition: "Warm",
    alertLevel: "normal",
    provider: "Demo weather provider",
    observedAt: "2026-07-06T07:00:00.000Z"
  },
  {
    id: "weather-zagreb",
    cityId: "city-zagreb",
    temperatureC: 33,
    condition: "Hot",
    alertLevel: "watch",
    provider: "Demo weather provider",
    observedAt: "2026-07-06T07:00:00.000Z"
  },
  {
    id: "weather-nicosia",
    cityId: "city-nicosia",
    temperatureC: 38,
    condition: "Heat advisory",
    alertLevel: "high",
    provider: "Demo weather provider",
    observedAt: "2026-07-06T07:00:00.000Z"
  }
];
